FROM mambaorg/micromamba:2.3.3@sha256:800e7ade3ffe29c9a9ac2026163131495f8197c3852e572c5835beb4e8a33cd6
USER root
RUN micromamba install -y -n base -c https://conda.software.inl.gov/public -c conda-forge \
    moose=2026.09.13 python=3.14 numpy meshio netcdf4 \
    && micromamba list -n base --explicit > /opt/package-lock.txt \
    && micromamba clean --all --yes
ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    OMP_NUM_THREADS=2 OPENBLAS_NUM_THREADS=2
WORKDIR /work
